Repository harakeke-2019/feke, pull requests merged in 2019-02, with the labels that each got.

#11 5 welcome
  client/components/App.jsx
  client/components/Home.jsx
  client/index.js
  server/index.js
  server/public/bundle.js
  server/public/bundle.js.map
Labels: Client

#12 1 setup db with metadata tables
  dev.sqlite3
  migrations/20190228150114_feke.js
  migrations/20190228150540_category.js
  migrations/20190228150644_content.js
  seeds/category.js
  seeds/content.js
  seeds/feke.js
Labels: db

#13 Re-ordered seed structure
  seeds/content.js
Labels: High Priority, db

#16 update routes to retrieve the feke
  server/routes/feke.js
  server/server.js
Labels: Routes

#17 Added template images to Public folder
  server/public/images/Home.png
  server/public/images/categories.png
  server/public/images/chooseFeke.png
  server/public/images/createFeke.png
  server/public/images/unnamed.png
  server/public/images/welcome.png
Labels: Style

#38 Added semantic-ui
  server/public/index.html
Labels: Style
