Repository harakeke-2019/feke, pull requests merged in 2019-03, with the labels that each got.

#61 Create category api
  client/api/category.js
  client/api/food.js
  server/public/bundle.js
  server/public/bundle.js.map
  server/routes/category.js
Labels: Api, Client, High Priority

#65 Created category actions
  client/Actions/index.js
  client/actions/index.js
  client/api/family.js
  client/api/numbers.js
Labels: Api, Client, High Priority

#66 60 db addfeke function
  server/db/feke.js
  server/routes/feke.js
Labels: db

#69 Created content reducer
  client/Actions/index.js
  client/reducers/content.js
  client/reducers/index.js
Labels: Client, High Priority

#72 Created isLoading reducer
  client/reducers/index.js
  client/reducers/isLoading.js
Labels: Client

#112 104 adding more categories to db
  seeds/category.js
  seeds/content.js
Labels: db

#114 Added 'questions' table and filled seed in DB
  client/Actions/getFeke.js
  migrations/20190304113537_questions.js
  seeds/questions.js
Labels: Server, db

#118 113 create answer options table
  migrations/20190304121702_answerOptions.js
  seeds/answerOptions.js
Labels: Server, db

#137 134 add more questions to db
  client/components/Progressbar.jsx
  dev.sqlite3-journal
  seeds/answerOptions.js
  seeds/questions.js
Labels: Server, db

#141 139 fix db answers
  dev.sqlite3-journal
  seeds/answerOptions.js
Labels: Server, db

#150 147 centre quiz contents
  client/components/Quiz.jsx
  server/public/main.css
Labels: Client, Style

#162 Corrected capitalization requirements
  seeds/answerOptions.js
Labels: db
